### ISSUE TITLE
license and comparison info?

### ISSUE THREAD

**Issue by EricZimmerman** [moaistory/winsearchdbanalyzer#4]
Any chance you can change this to MIT? i would love to take a look at your ese parsing code and compare it for accuracy with using native windows functions, etc.

it would be nice to have the ese parser split out into a nuget package, etc so it can be used by other projects more easily too.

right now i have several tools, and more planned, targeting ese and am currently using microsoft's managed library for this.

the parser here, being all C#, and recovering deleted, would be a better choice tho.

if you havent seen my contributions to windows forensics/c# stuff, check out my repos. =)

Please let me know. i would love to have a native ese parser (without me having to write one myself).

**Comment by moaistory** [comment]
This code was developed when I was a student. I am not working on forensics. I have no intention of updating. Should I update this code additionally after changing the license?

**Comment by EricZimmerman** [comment]
If you make it mit I'll roll with more testing and updates. I will keep
your name in the codebase as well.

**Comment by EricZimmerman** [comment]
any further thoughts on this?

**Comment by moaistory** [comment]
I changed the license.
I hope my project will be useful to many people.

**Comment by EricZimmerman** [comment]
awesome thanks!!
